name:  Workflow Template
description: "Composite Action Template"
inputs:  
  command:
    required: true

runs:
  using: "composite"
  steps:    
    - name: Build ,Version Set,Unit Test
      if: ${{ inputs.command }}
      run: ${{ inputs.command }}
      shell: bash
      
    - name: Sonar Scan
      if: ${{ env.sonar_commands }}
      uses: lumada-common-services/gh-composite-actions@sonar-action      
      
    - name: OWASP Scan
      if: ${{ env.owasp_Project }}
      uses: dependency-check/Dependency-Check_Action@main
      id: owasp
      with:
        project: ${{ env.owasp_Project }}
        path: '.'
        format: 'ALL'
        out: 'reports'
        args: >
            --disableNodeJS \
            --disableAssembly \
            --disableYarnAudit \
            --enableRetired
      
    - name: Create Tag
      if: ${{ env.Tag_version }}
      uses: actions/github-script@v5
      with:
        script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ env.Tag_version }}',
              sha: context.sha
            })

    - name: Publish Artifacts to Registry
      if: ${{ env.artifacts_manifest_file }}
      continue-on-error: false
      uses: lumada-common-services/registry-publication@v1
      with:
        ARTIFACTS_CONFIG_FILE: ${{ env.artifacts_manifest_file }}
        ARTIFACTORY_APIKEY: ${{ env.artifactory_api_key }}
        ARTIFACTORY_USER: ${{ env.artifactory_user }}
        BUILD_NUMBER: ${{ env.run_number }}
        BUILD_NAME: ${{ env.job }}
        BUILD_VERSION: ${{ env.pkg_version }}
        WORKSPACE: ${{ env.workspace }}
        BUILD_URL: ${{ env.build_url }}
