name: "Pull Request Composite Action Template"
description: "Composite Action Template For Pull Request"

runs:
  using: "composite"
  steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Code Linting
      if: ${{ env.lint_commands }}
      uses: lumada-common-services/gh-composite-actions@YKN-174

    - name: Maven Build
      if: ${{ env.maven_commands }}
      uses: lumada-common-services/gh-composite-actions@YKN-161
          