name: "Pull Request Composite Action Template"
description: "Composite Action Template For Pull Request"
inputs:
  lintimage:
    description: Docker Image to be used
    required: false
    default: node:14

runs:
  using: "docker"
  image: "Dockerfile"
  env:
    LINTIMAGE=${INPUT_LINTIMAGE}
