name:  "Helm deployment GitHub Action"
description: "Helm deployment GitHub Action"
inputs:
  APP_VERSION:
    description: "New version of solution and app definitions"
    required: true
  JFROG_USERNAME:
    description: "User name for https://hitachi.jfrog.io/"
    default: 'devops-service-cicd'
    required: true
  JFROG_PASSWORD:
    description: "Password for https://hitachi.jfrog.io/"
    required: true

runs:
  using: "composite"
  steps:    
      - name: set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.11.1'
          # token: "nope-not-going-to-provide"
        
      - name: Deploy helm charts
        if: ${{ inputs.DEPLOYMENT_METHOD }} == "Helm"
        run: |
        
          # print out version to be used
          echo "helm deployment for version ${APP_VERSION}"

          # updating kubeconfig
          cat ${JARJAR_CLUSER_KUBECONFIG} > kubeconfig

          # add helm registry
          echo "Adding helm registry https://hitachi.jfrog.io/artifactory/api/helm/csaf-helm-dev as csaf-helm-dev"
          helm repo add csaf-helm-dev https://hitachi.jfrog.io/artifactory/api/helm/csaf-helm-dev --username ${{ inputs.JFROG_USERNAME }} --password ${{ inputs.JFROG_PASSWORD }}
          helm repo update
          
          # echo "helm list"
          helm list --kubeconfig kubeconfig
          
          # install helm charts
          helm install lumadasolution-definition csaf-helm-dev/hello-world-solutiondefinition --version ${APP_VERSION} --kubeconfig kubeconfig
          helm install hello-world-definition csaf-helm-dev/hello-world-lumadaappdefinition --version ${APP_VERSION} --kubeconfig kubeconfig
          
        shell: bash
  
  
