name: Build Docker Container Image
description: "Composite Action for build, push and tag docker image"

inputs:
  ARTIFACTORY:
    description: "Name of the artifactory where docker image will get publish."
    required: true

  ARTIFACTORY_USER:
    description: "Username of the artifactory"
    required: true

  ARTIFACTORY_KEY:
    description: "Access token for the artifactory"
    required: true

  IMAGE_PREFIX:
    description: "If a prefix is needed to distinguish git tags for docker image build."
    required: true
  
  DOCKERFILE_PATH:
    description: "Path where the dockerfile resides in github repository."
    required: true

  TAG_SUFFIX:
    description: " If present, it will be added to the image tag." 
    required: false  
            
runs:
  using: "composite"
  steps:

    - name: Update image tag
      run: |
        if '${{ inputs.TAG_SUFFIX != '' }}' ; then
          IMAGE_TAG=$(date +'%Y%m%d').${GITHUB_RUN_NUMBER}-${{inputs.TAG_SUFFIX}}
        else
          IMAGE_TAG=$(date +'%Y%m%d').${GITHUB_RUN_NUMBER}
        fi
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
        echo "IMAGE=${GITHUB_REPOSITORY}:$IMAGE_TAG" >> $GITHUB_ENV
      shell: bash
    
    - name: Build
      id: build-image
      run: |
        docker build -t "${{ inputs.ARTIFACTORY }}/${{ env.IMAGE }}" -f ${{inputs.DOCKERFILE_PATH}} .
      shell: bash

    - name: Push to Artifactory
      id: push-to-artifactory
      run: |
        docker login ${{ inputs.ARTIFACTORY }} -u ${{ inputs.ARTIFACTORY_USER }} -p ${{ inputs.ARTIFACTORY_KEY }}
        docker push "${{ inputs.ARTIFACTORY }}/${{ env.IMAGE }}"
      shell: bash

    - name: Summary
      run: |
        echo "Image built:"\ >> $GITHUB_STEP_SUMMARY
        echo "<pre>" >> $GITHUB_STEP_SUMMARY
        docker images >> $GITHUB_STEP_SUMMARY
        echo "</pre>"\ >> $GITHUB_STEP_SUMMARY
        echo "Image pushed: '${{ inputs.ARTIFACTORY }}/${{ env.IMAGE }}'" >> $GITHUB_STEP_SUMMARY
      shell: bash
    
    - uses: rickstaa/action-create-tag@v1
      with:
        tag: "${{inputs.IMAGE_PREFIX}}-${{ env.IMAGE_TAG }}"
        message: "${{ inputs.ARTIFACTORY }}/${{ env.IMAGE }}"      
