name:  "kubectl deployment GitHub Action"
description: "kubectl deployment GitHub Action"
inputs:
  DEPLOYMENT_METHOD:
    description: "Deployment type either ArgoCD or helm or kubectl"
    required: true
  SOLUTIONDEFINITION_YAML:
    description: "Path to the template file where action file need to update the new Version of solution"
    required: true
  APP_DEFINITION_YAML:
    description: "Path to the appdefinition file"
    required: true
#   APP_VERSION:
#     description: "New version of solution and app definitions"
#     required: true
  CLUSTERKUBECONFIG:
    description: "New version of configfile"
    required: true
    

runs:
  using: "composite"
  steps:    
    - name: kubectl deploy
      if: ${{ inputs.DEPLOYMENT_METHOD }} == "KUBECTL"
      run: |
        echo "Doing deployment with kubectl"
        echo "${{ inputs.CLUSTERKUBECONFIG }}" > $RUNNER_TEMP/config
        kubectl apply -f ${{ inputs.SOLUTIONDEFINITION_YAML }} --kubeconfig $RUNNER_TEMP/config
        kubectl apply -f ${{ inputs.APP_DEFINITION_YAML }} --kubeconfig $RUNNER_TEMP/config
      shell: bash
