name: "Pull Request Composite Action Template"
description: "Composite Action Template For Pull Request"

inputs:
  working-directory:
    description: "Working Directory"
    required: true
    default: "."

  gradle_image:
    description: "Docker Image to be used"  
    required: true
    default: gradle

  gradle_tag:
    description: "Tag of the Docker image to be used. Default tag is latest"  
    required: true
    default: 7.5.1-jdk11-alpine

  gardle_commands:
    description: "Command to run"  
    required: true

  perform_gradle_build:
    required: true
    type: boolean
    default: false
    
  sonar_project_key:
    description: "Project key"  
    required: true  
  
  sonar_host_url:
     description: "Project key"  
     required: true
     
  sonar_login:
    description: "Project key"  
    required: true
  
  perform_sonar_scan:
    required: true
    type: boolean
    default: false
  

runs:
  using: "composite"
  steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Gradle Build
      if: ${{ inputs.perform_gradle_build == 'true'}}    
      uses: lumada-data-services/lds-composite-action@build-action
      with:
        working-directory: ${{ inputs.working-directory }}
        gradle_image: ${{ inputs.gradle_image }}
        gradle_tag: ${{ inputs.gradle_tag }}
        gradle_commands: ${{ inputs.gradle_commands }}

    - name: Sonar Scan
      if: ${{ inputs.perform_sonar_scan == 'true'}}    
      uses: lumada-data-services/lds-composite-action@sonar-action
      with:
        sonar_project_key: ${{ inputs.sonar_project_key }}
        sonar_host_url: ${{ inputs.sonar_host_url }}
        sonar_login: ${{ inputs.sonar_login}}    
