name:  Workflow Template
description: "Composite Action Template"
inputs:

  JF_URL:
    required: true
    
  JF_ACCESS_TOKEN:
    required: true
    
  JF_GIT_TOKEN:
    required: true
    
  RUN_FROGBOT:
    required: true

runs:
  using: "composite"
  steps:
      
    - name: FrogBot
      if: $${{ env.RUN_FROGBOT }}
      uses: jfrog/frogbot@v2
      with:
        JF_URL: ${{ inputs.JF_URL }}
        JF_ACCESS_TOKEN: ${{ inputs.JF_ACCESS_TOKEN }}
        JF_GIT_TOKEN: ${{ inputs.JF_GIT_TOKEN }}
