name:  "Helm deployment GitHub Action"
description: "Helm deployment GitHub Action"
inputs:
  APP_VERSION:
    description: "New version of solution and app definitions"
    required: true
  JFROG_USERNAME:
    description: "User name for https://hitachi.jfrog.io/"
    default: 'devops-service-cicd'
    required: true
  JFROG_PASSWORD:
    description: "Password for https://hitachi.jfrog.io/"
    required: true
  CLUSTERKUBECONFIG:
    description: "New version of configfile"
    required: true
#   SOLUTION_DEFINATION_CHART_PATH:
#     description: "Pass solution definition chart path from git repo"
#     required: true
#   APP_DEFINITION_CHART_PATH:
#     description: "Pass app definition chart path from git repo"
#     required: true

runs:
  using: "composite"
  steps:    
      - name: set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.11.1'
          # token: "nope-not-going-to-provide"
          
      - name: Setup kubectl 
        id: install-kubectl
        uses: azure/setup-kubectl@v3
        
      - name: Deploy helm charts
        if: ${{ inputs.DEPLOYMENT_METHOD }} == "Helm"
        run: |
          echo "${{ inputs.CLUSTERKUBECONFIG }}" > $RUNNER_TEMP/config
          kubectl get pods -A --kubeconfig $RUNNER_TEMP/config


          # print out version to be used
          # echo "helm deployment for version ${APP_VERSION}"

          # updating kubeconfig
          
          # echo "${AKS_JARJAR_01_KUBECONFIG}" > config
          # chmod 600 config

          # add helm registry
          # echo "Adding helm registry https://hitachi.jfrog.io/artifactory/api/helm/csaf-helm-dev as csaf-helm-dev"
          # helm repo add csaf-helm-dev https://hitachi.jfrog.io/artifactory/api/helm/csaf-helm-dev --username ${{ inputs.JFROG_USERNAME }} --password ${{ inputs.JFROG_PASSWORD }}
          # helm repo update --kubeconfig config
          
          # echo "helm list"
          # helm list --kubeconfig config
          
          # install helm charts
          # helm install lumadasolution-definition-${APP_VERSION} csaf-helm-dev/hello-world-solutiondefinition --version ${APP_VERSION} --kubeconfig config
          # helm install hello-world-definition-${APP_VERSION} csaf-helm-dev/hello-world-lumadaappdefinition --version ${APP_VERSION} --kubeconfig config
          
        shell: bash

