name: Release Drafter
on:
  push:
    branches: [master]
  # when release is done release.md file is updated by automatic commit github action so to avoid trigger of release-drafter added paths-ignore
    paths-ignore: ['docs/release.md']

  # pull_request event is required only for autolabeler
  pull_request:
    branches: [master]
  # Only following types are handled by the action, but one can default to all as well
    types: [opened,edited]

permissions:
  contents: read

jobs:
  create_release_draft:
    permissions:
      # write permission is required to create a github release
      contents: write
      # write permission is required for autolabeler
      # otherwise, read permission is required at least
      pull-requests: write
    runs-on: [k8s]
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "master"
      - uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter-config.yml
          disable-autolabeler: false
        env:
          GITHUB_TOKEN: ${{ secrets.HV_ADMIN_GITHUB_TOKEN }}
